version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=test
    ports:
      - '54320:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./src/assets/db/init_2.sql:/docker-entrypoint-initdb.d/init_2.sql
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - '63790:6379'
  app:
    container_name: bms-app
    build: .
    image: bms-app
    depends_on:
      - db
      - redis
    ports:
      - 19230:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    links:
      - db
      - redis
    volumes:
      - './:/team_pandas'
      - '/team_pandas/node_modules'
volumes:
  postgres:
    driver: local